### PR TITLE
Better styling on mobile

### PR DESCRIPTION
**Pull request by edellucien**
Better styling on mobile

### CODE REVIEW

**Review by friedjoff — CHANGES_REQUESTED** [review]
Why do we need `isMobile` in our Redux store? I would prefer CSS breakpoints.

**Comment by edellucien** [comment]
> Why do we need `isMobile` in our Redux store? I would prefer CSS breakpoints.

To change some labels and Grid values for mobile as well.
I can switch to css breakpoints if you prefer

**Comment by friedjoff** [comment]
Ok, better lets's use breakpoints. You can completely hide mobile lables and grid values on desktop using CSS.

**Comment by friedjoff** [comment]
Code looks good now!

The UI can still be improved a bit on small screens:

grafik

**Review by friedjoff — CHANGES_REQUESTED** [review]
See comment above.

**Review by friedjoff — APPROVED** [review]
Sorry, I've tested master.

LGTM!

**Pull request merged**
